development:
  adapter: mysql2
  database: anketa_dev
  encoding: utf8
  username: root
  password: legenda
  host: 127.0.0.1
  pool: 5
  timeout: 5000


production:
  adapter: mysql2
  database: anketa_dev
  encoding: utf8
  username: root
  password: legenda
  host: 127.0.0.1
  pool: 5
  timeout: 5000
